### ISSUE TITLE
[Bug] 'too many filter conditions specified' on reasonable query

### ISSUE THREAD

**Issue by jwaaang** [temporalio/sdk-typescript#1087]
### What are you really trying to do?

I am trying to get a list of active workflowIds using temporal client.

### Describe the bug

I am trying to query all executions that are running and have some workflow name, when i run it i get:

```
/Users/jackwang/scaleapi/.yarn/cache/@grpc-grpc-js-npm-1.7.3-367eafd856-cb05aae459.zip/node_modules/@grpc/grpc-js/src/call.ts:81
  const error = new Error(message);
                ^
Error: 2 UNKNOWN: too many filter conditions specified
    at Object.callErrorFromStatus (/Users/jackwang/scaleapi/.yarn/cache/@grpc-grpc-js-npm-1.7.3-367eafd856-cb05aae459.zip/node_modules/@grpc/grpc-js/src/call.ts:81:17)
    at Object.onReceiveStatus (/Users/jackwang/scaleapi/.yarn/cache/@grpc-grpc-js-npm-1.7.3-367eafd856-cb05aae459.zip/node_modules/@grpc/grpc-js/src/client.ts:358:36)
    at /Users/jackwang/scaleapi/.yarn/cache/@grpc-grpc-js-npm-1.7.3-367eafd856-cb05aae459.zip/node_modules/@grpc/grpc-js/src/call-stream.ts:210:27
    at Object.onReceiveStatus (/Users/jackwang/scaleapi/.yarn/cache/@temporalio-client-npm-1.6.0-8d36687867-ed8c23c572.zip/node_modules/@temporalio/client/src/grpc-retry.ts:176:17)
    at Object.onReceiveStatus (/Users/jackwang/scaleapi/.yarn/cache/@grpc-grpc-js-npm-1.7.3-367eafd856-cb05aae459.zip/node_modules/@grpc/grpc-js/src/client-interceptors.ts:462:34)
    at Object.onReceiveStatus (/Users/jackwang/scaleapi/.yarn/cache/@grpc-grpc-js-npm-1.7.3-367eafd856-cb05aae459.zip/node_modules/@grpc/grpc-js/src/client-interceptors.ts:424:48)
    at /Users/jackwang/scaleapi/.yarn/cache/@grpc-grpc-js-npm-1.7.3-367eafd856-cb05aae459.zip/node_modules/@grpc/grpc-js/src/call-stream.ts:334:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/Users/jackwang/scaleapi/.yarn/cache/@grpc-grpc-js-npm-1.7.3-367eafd856-cb05aae459.zip/node_modules/@grpc/grpc-js/src/client.ts:328:30)
    at callMethod (/Users/jackwang/scaleapi/.yarn/unplugged/dd-trace-patch-1a35c08d8a/node_modules/dd-trace/packages/datadog-instrumentations/src/grpc/client.js:144:51)
    at ServiceClientImpl.makeUnaryRequest (/Users/jackwang/scaleapi/.yarn/unplugged/dd-trace-patch-1a35c08d8a/node_modules/dd-trace/packages/datadog-instrumentations/src/grpc/client.js:19:14)
    at Service.rpcImpl (/Users/jackwang/scaleapi/.yarn/cache/@temporalio-client-npm-1.6.0-8d36687867-ed8c23c572.zip/node_modules/@temporalio/client/src/connection.ts:341:21)
    at Service.rpcCall (/Users/jackwang/scaleapi/.yarn/unplugged/protobufjs-npm-7.0.0-caea7a2a3b/node_modules/protobufjs/src/rpc/service.js:94:21)
    at executor (/Users/jackwang/scaleapi/.yarn/cache/@protobufjs-aspromise-npm-1.1.2-71d00b938f-011fe7ef08.zip/node_modules/@protobufjs/aspromise/index.js:44:16)
    at new Promise (<anonymous>)
    at Object.asPromise (/Users/jackwang/scaleapi/.yarn/cache/@protobufjs-aspromise-npm-1.1.2-71d00b938f-011fe7ef08.zip/node_modules/@protobufjs/aspromise/index.js:28:12)
    at Service.rpcCall (/Users/jackwang/scaleapi/.yarn/unplugged/protobufjs-npm-7.0.0-caea7a2a3b/node_modules/protobufjs/src/rpc/service.js:86:21)
    at Service.listWorkflowExecutions (eval at Codegen (/Users/jackwang/scaleapi/.yarn/cache/@protobufjs-codegen-npm-2.0.4-36e188bbe6-59240c850b.zip/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:4:15)
    at WorkflowClient._list (/Users/jackwang/scaleapi/.yarn/cache/@temporalio-client-npm-1.6.0-8d36687867-ed8c23c572.zip/node_modules/@temporalio/client/src/workflow-client.ts:926:51)
    at _list.next (<anonymous>)
    at /Users/jackwang/scaleapi/packages/task-pipeline/src/scripts/query-open-workflows.ts:23:5
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async bootstrap (/Users/jackwang/scaleapi/packages/task-pipeline/src/scripts/main.ts:10:5) {
  code: 2,
  details: 'too many filter conditions specified',
  metadata: Metadata {
    internalRepr: Map(1) { 'content-type' => [Array] },
    options: {}
  }
}
```

### Minimal Reproduction
```
  const connection = await Connection.connect({address: TEMPORAL_ADDRESS});
  const count = await connection.workflowService.countWorkflowExecutions({namespace: 'default', query: `WorkflowType="orchestratePipeline" and ExecutionStatus="Running"`});
  console.log(JSON.stringify(count.count));
  let execs;
  const activeExecIds: string[] = [];

  const counter = 0;
  const client = app.get<WorkflowClient>(TEMPORAL_QUEUE_TOKEN);
  for await (const workflow of client.list({
    query: `WorkflowType="orchestratePipeline" and ExecutionStatus="Running"`,
    pageSize: 5,
  })) {
    console.log(workflow);
  }
```
### Environment/Versions

- OS and processor: M1 Mac
- Temporal Version: 1.6.0
- Are you using Docker or Kubernetes or building Temporal from source? Temporal is on kubernetes

### Additional context

Weirdly enough this script (with the same query string) works for me:
```
  const connection = await Connection.connect({address: TEMPORAL_ADDRESS});
  const count = await connection.workflowService.countWorkflowExecutions({namespace: 'default', query: `WorkflowType="orchestratePipeline" and ExecutionStatus="Running"`});
  console.log(JSON.stringify(count.count));
  let execs;
  const activeExecIds: string[] = [];

  const counter = 0;
  do {
    if (counter % 50 === 0) {
      console.log(activeExecIds[activeExecIds.length - 1]);
      console.log(activeExecIds.length);
    }
    execs = await connection.workflowService.listWorkflowExecutions({
      namespace: 'default',
      pageSize: 5,
      query: `WorkflowType="orchestratePipeline" and ExecutionStatus="Running"`,
      nextPageToken: execs ? execs.nextPageToken : null,
    });
    execs.executions.map(exec => {
      if (exec.execution?.workflowId) {
        activeExecIds.push(exec.execution?.workflowId);
      }
    });
  } while(execs && execs.nextPageToken)
  const csvStr = activeExecIds.join("\n");
  fs.writeFileSync(FILE_TO_WRITE_TO, csvStr);
```
but i think i am not using `nextPageToken` correctly since this infinite loops and i get back duplicate workflows. Am also curious to what i am doing wrong here.

**Comment by bergundy** [comment]
Which temporal server version are you using with which persistence option?
It's not an SDK bug, it's a server limitation.

**Comment by jwaaang** [comment]
Temporal server version is: 1.17.0
We are using scyllaDB as persistence but it should be functionally the same as cassandra

**Comment by bergundy** [comment]
Are you using ElasticSearch for the visibility database?
Cassandra doesn't support enhanced visibility.

Closing because this isn't an SDK issue.

**Comment by lorensr** [comment]
Jack—these docs pages might help:

https://docs.temporal.io/visibility

https://docs.temporal.io/cluster-deployment-guide

And feel free to post questions to https://community.temporal.io/c/support/5
