### ISSUE TITLE
[Bug] Duplicate name error when @temporalio/worker and @temporalio/testing both installed

### ISSUE THREAD

**Issue by solastley** [temporalio/sdk-typescript#1100]
### What are you really trying to do?
Trying to add unit tests for my Temporal code by installing `@temporalio/testing`, writing unit tests which depend on it, and building/running the tests.

### Describe the bug
When I install both packages and attempt to run the tests (or run a worker locally), I get a namespace error:

```
/<redacted>/node_modules/protobufjs/src/namespace.js:239
                throw Error("duplicate name '" + object.name + "' in " + this);
                      ^
Error: duplicate name 'ActivityHeartbeat' in Namespace coresdk
    at Namespace.add (/<redacted>/node_modules/protobufjs/src/namespace.js:239:23)
    at Root.add (/<redacted>/node_modules/protobufjs/src/namespace.js:232:28)
    at Root.addJSON (/<redacted>/node_modules/protobufjs/src/namespace.js:172:16)
    at Object.<anonymous> (/<redacted>/node_modules/@temporalio/worker/node_modules/@temporalio/proto/protos/json-module.js:7:2)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.require.extensions.<computed> [as .js] (/<redacted>/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
```

### Minimal Reproduction
Install `@temporalio/worker` and `@temporalio/testing`, try to run tests with jest.

### Environment/Versions
Development environment

deps:
```
"@temporalio/activity": "^1.7.0",
"@temporalio/client": "^1.7.0",
"@temporalio/worker": "^1.7.0",
"@temporalio/workflow": "^1.7.0",
```

dev deps:
```
"@temporalio/testing": "^1.7.2",
```

**Comment by bergundy** [comment]
Please use the same version of of the `@temporalio/*` packages, it should prevent this from happening.

**Comment by solastley** [comment]
That fixed it, thanks for the quick reply! <3
