### ISSUE TITLE
[Bug] Workflow Bundler does not deny usage of the `process` global variable

### ISSUE THREAD

**Issue by mjameswh** [temporalio/sdk-typescript#1112]
### Describe the bug

The Workflow Bundler does not forbid uses of the `process` global variable inside Workflow code, resulting in `ReferenceError: process is not defined` at Workflow execution.

### Minimal Reproduction

1. Add something like `process.getuid()` to any existing workflow (note that no `import` statement is added as `process` is a global variable exposed by Node).

2. Start the worker, and confirm the workflow code compiles without error:

```
[INFO] asset workflow-bundle-09308af9a4bcd2033177.js 726 KiB [emitted] [immutable] (name: main)
[INFO] runtime modules 937 bytes 4 modules
[INFO] modules by path ./node_modules/@temporalio/ 168 KiB
[INFO]   modules by path ./node_modules/@temporalio/common/lib/ 69.1 KiB 18 modules
[INFO]   modules by path ./node_modules/@temporalio/workflow/ 97.1 KiB
[INFO]     ./node_modules/@temporalio/workflow/lib/worker-interface.js 11 KiB [built] [code generated]
[INFO]     + 13 modules
[INFO]   ./node_modules/@temporalio/worker/lib/workflow-log-interceptor.js 2.27 KiB [built] [code generated]
[INFO] modules by path ./src/ 3.73 KiB
[INFO]   ./src/workflows-autogenerated-entrypoint.cjs 575 bytes [built] [code generated]
[INFO]   ./src/workflows.ts 2.9 KiB [built] [code generated]
[INFO]   ./src/shared.ts 270 bytes [built] [code generated]
[INFO] __temporal_custom_payload_converter (ignored) 15 bytes [built] [code generated]
[INFO] __temporal_custom_failure_converter (ignored) 15 bytes [built] [code generated]
[INFO] ./node_modules/long/umd/index.js 43.1 KiB [built] [code generated]
[INFO] ./node_modules/ms/index.js 2.95 KiB [built] [code generated]
[INFO] webpack 5.77.0 compiled successfully in 223 ms
[INFO] Workflow bundle created { size: '0.71MB' }
[INFO] Worker state changed { state: 'RUNNING' }
```

3. Start a Workflow excution, then observe an error message similar to this one in Worker's log:
```
[ERROR] Failed to activate workflow {
  runId: '6898d7d0-6622-4cca-928f-2aa2577e6221',
  error: /Users/.../samples-typescript/mutex/workflow-bundle-09308af9a4bcd2033177.js:4594
  const C = process.env.SOMETHING;
            ^
  
  ReferenceError: process is not defined
      at process (/Users/.../samples-typescript/mutex/src/workflows.ts:26:10)
      at __webpack_require__ (webpack/bootstrap:19:0)
      at importWorkflows (/Users/.../samples-typescript/mutex/src/workflows-autogenerated-entrypoint.cjs:9:9)
      at Object.initRuntime (/Users/.../samples-typescript/mutex/node_modules/@temporalio/workflow/src/worker-interface.ts:138:14)
      at evalmachine.<anonymous>:1:18
      at Script.runInContext (node:vm:134:12)
      at Object.runInContext (node:vm:284:6)
      at Proxy.<anonymous> (/Users/.../samples-typescript/mutex/node_modules/@temporalio/worker/lib/workflow/vm.js:36:46)
      at VMWorkflowCreator.createWorkflow (/Users/.../samples-typescript/mutex/node_modules/@temporalio/worker/lib/workflow/vm.js:43:24)
      at async handleRequest (/Users/.../samples-typescript/mutex/node_modules/@temporalio/worker/lib/workflow/workflow-worker-thread.js:42:13),
  workflowExists: false
}
```

**Comment by nubunto** [comment]
is this a good first issue? I'm inclined to tackle this.

**Comment by mjameswh** [comment]
> is this a good first issue? I'm inclined to tackle this.

Thanks for offering! I expect this might actually be a little bit tricky to fix, but not that bad if you are comfortable digging into Webpack. Plus it's possible that I may have missed some straight forward solution.

So let me give some context on this.

The thing is that webpack has a built-in knowledge of which globals (such as `process`, `require` or `JSON`) exist based on the build `target` (see [here](https://webpack.js.org/configuration/target/)). As out bundler is not explicitly setting this parameter at the moment, Webpack defaults to `web`, which is obviously wrong, yet reasonably close from the sandbox environment. The `node` target would be worst, as it would suppose that the `require` global function exists, which we definitely don't want.

Setting target to `false` would actually be the closest we can get of what the sandbox environment really is, but that brings up other issues because of libraries using ["conditional package.json exports"](https://nodejs.org/api/packages.html#conditional-exports). These libraries (including some that we ourselves depends on) very often expose a `node` and a `browser` variant, making them impossible to use when target is set to anything else than `node` or `web`. By the way, what I just described here is also the reason behind [this other issue](https://github.com/temporalio/sdk-typescript/issues/958).

There's certainly more than one way to fix this, but I think the most appropriate solution would be to define a new, custom Webpack target that closely match the workflow sandbox environment. That custom target would also need to enable the "browser" conditional, to ensure that we don't break external libraries that depends on it.
