### ISSUE TITLE
[Bug] `RangeError: Maximum call stack size exceeded` on Worker shutdown

### ISSUE THREAD

**Issue by mjameswh** [temporalio/sdk-typescript#1224]
### Describe the bug

Two slack users reported seeing Worker crashes at shutdown time (after reaching the 'STOPPED' state), with the following error message:

```
RangeError: Maximum call stack size exceeded
    at OperatorSubscriber.<anonymous> (<appFolder>/node_modules/@temporalio/worker/node_modules/rxjs/src/internal/util/lift.ts:26:16)
    at <appFolder>/node_modules/@temporalio/worker/node_modules/rxjs/src/internal/Observable.ts:226:22
    at Object.errorContext (<appFolder>/node_modules/@temporalio/worker/node_modules/rxjs/src/internal/util/errorContext.ts:29:5)
    at Observable.subscribe (<appFolder>/node_modules/@temporalio/worker/node_modules/rxjs/src/internal/Observable.ts:220:5)
    at subscribeToSource (<appFolder>/node_modules/@temporalio/worker/node_modules/rxjs/src/internal/operators/repeat.ts:151:30)
    at resubscribe (<appFolder>/node_modules/@temporalio/worker/node_modules/rxjs/src/internal/operators/repeat.ts:145:13)
    at subscribeToSource (<appFolder>/node_modules/@temporalio/worker/node_modules/rxjs/src/internal/operators/repeat.ts:166:13)
( ... 6438 lines removed, jumping between repeat.ts:166:13 and repeat.ts:145:13 )
    at resubscribe (<appFolder>/node_modules/@temporalio/worker/node_modules/rxjs/src/internal/operators/repeat.ts:145:13)
    at <appFolder>/node_modules/@temporalio/worker/node_modules/rxjs/src/internal/operators/repeat.ts:155:19
    at OperatorSubscriber._this._complete (<appFolder>/node_modules/@temporalio/worker/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:92:13)
    at OperatorSubscriber.Subscriber.complete (<appFolder>/node_modules/@temporalio/worker/node_modules/rxjs/src/internal/Subscriber.ts:106:12)
    at checkComplete (<appFolder>/node_modules/@temporalio/worker/node_modules/rxjs/src/internal/operators/mergeInternals.ts:48:18)
    at OperatorSubscriber.onFinalize (<appFolder>/node_modules/@temporalio/worker/node_modules/rxjs/src/internal/operators/mergeInternals.ts:125:15)
    at OperatorSubscriber.unsubscribe (<appFolder>/node_modules/@temporalio/worker/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:109:33)
    at OperatorSubscriber._this._complete (<appFolder>/node_modules/@temporalio/worker/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:98:18)
    at OperatorSubscriber.Subscriber.complete (<appFolder>/node_modules/@temporalio/worker/node_modules/rxjs/src/internal/Subscriber.ts:106:12)
    at OperatorSubscriber.Subscriber._complete (<appFolder>/node_modules/@temporalio/worker/node_modules/rxjs/src/internal/Subscriber.ts:132:24)
    at OperatorSubscriber.Subscriber.complete (<appFolder>/node_modules/@temporalio/worker/node_modules/rxjs/src/internal/Subscriber.ts:106:12)
    at <appFolder>/node_modules/@temporalio/worker/node_modules/rxjs/src/internal/operators/take.ts:65:28
    at OperatorSubscriber._this._next (<appFolder>/node_modules/@temporalio/worker/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
    at OperatorSubscriber.Subscriber.next (<appFolder>/node_modules/@temporalio/worker/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
    at AsyncAction.<anonymous> (<appFolder>/node_modules/@temporalio/worker/node_modules/rxjs/src/internal/observable/timer.ts:173:20)
    at AsyncAction._execute (<appFolder>/node_modules/@temporalio/worker/node_modules/rxjs/src/internal/scheduler/AsyncAction.ts:120:12)
    at AsyncAction.execute (<appFolder>/node_modules/@temporalio/worker/node_modules/rxjs/src/internal/scheduler/AsyncAction.ts:95:24)
    at AsyncScheduler.flush (<appFolder>/node_modules/@temporalio/worker/node_modules/rxjs/src/internal/scheduler/AsyncScheduler.ts:40:27)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
```

This only happens if using log forwarding:

```
Runtime.install({ 
  telemetryOptions: { logging: { forward: { level: 'INFO' } } },
  // ... other options
});
```

No error is thrown if logging options are changed to the following:

```
Runtime.install({ 
  telemetryOptions: { logging: { filter: makeTelemetryFilterString({ core: 'INFO', other: 'INFO' }) } },
  // ... other options
});
```

**Comment by bergundy** [comment]
Note that I attempted to fix this and reverted it here: https://github.com/temporalio/sdk-typescript/pull/1152/commits/5b1f83dfa936e3c75baa3625a810daf5aef86a21.

It caused a memory leak, probably due to TS being unable to keep up with the rate of log emission.

**Comment by mjameswh** [comment]
> Note that I attempted to fix this and reverted it here.

Oh, really? That's exactly what I had in mind a little bit earlier.

> It caused a memory leak, probably due to TS being unable to keep up with the rate of log emission.

That's strange... Why would rxjs be able to keep up, but pure TS code wouldn't? rxjs isn't magically making nodejs faster.

Can you give some details on what you mean exactly by memory leak here? I suppose that wouldn't be on rust side, as the message buffer gets emptied every time we poll from it. Was it simply that you went out of heap at some point, or were you observing a progressive increase in heap usage?

I get the feeling that this might be due to the fact that, in the refactored code, the `logs` array is being retained a bit too long (ie. it remains in scope while we sleep) and that's making it difficult for GC to collect back that memory. If that's the case, simply moving the "poll and process log entries" part out to a different function would fix it.

**Comment by mjameswh** [comment]
I restored your original attempt (as is) [here](https://github.com/temporalio/sdk-typescript/pull/1225).
