### ISSUE TITLE
[Bug] `nyc-test-coverage` is excessively difficult to use correctly

### ISSUE THREAD

**Issue by mjameswh** [temporalio/sdk-typescript#1233]
### Describe the bug

At the moment, using the `@temporalio/nyc-test-coverage` package to collect coverage data for Workflow tests is quite difficult and generally fragile. Though it works with appropriate setup (eg. we have a sample demonstrating that it works), some users are struggling at replicating that "winning combination" in their own project, despite considerable efforts and willingness to accept applicable constraints (eg. use Mocha or AVA, ts-node rather than ts-mocha or similar, pre-transpile TS code to pure-JS, hardcode workflow name in their test files to avoid importing wokrlfow.ts from tests, etc).

### What need to be done

This situation can be improved from two sides:
1. Improve the tool itself so that it is less fragile / more resilient to changes in its runtime environment
2. Provide clear instructions on how to use it

**Comment by mjameswh** [comment]
@jamespsterling Thanks for sharing your findings. Yes, I believe there's been a recent regression (possibly on our side) that made our `nyc-test-coverage` plugin fails in cases where it was previously working. What you are pointing at should help figure out where that regression lies.

**Comment by ilijaNL** [comment]
Any update on this?

**Comment by mjameswh** [comment]
> Any update on this?
Not yet, sorry.

**Comment by ilijaNL** [comment]
This area needs some improvement. We use a monorepo setup with jest (ts-jest as transformer). We have high code coverage requirement thus we using `collectCoverageFrom`. Somehow when we use the nyc-test-coverage package, the coverage is not merged correctly and we get really weird code coverage report. I assume this is due that the final sources are different between what ts-jest transforms and webpack (used by temporal sdk). 
This is kind of deal breaker atm.

**Comment by surjyams** [comment]
Is there any update on this? We are running into the same issue with @temporalio/nyc-test-coverage@1.10.1

**Comment by gaurav1999** [comment]
@mjameswh Facing same issue

```
● Test suite failed to run

    Invalid file coverage object, missing keys, found:data

      at assertValidObject (../node_modules/istanbul-lib-coverage/lib/file-coverage.js:38:15)
      at new FileCoverage (../node_modules/istanbul-lib-coverage/lib/file-coverage.js:214:9)
      at maybeConstruct (../node_modules/istanbul-lib-coverage/lib/coverage-map.js:15:12)
      at ../node_modules/istanbul-lib-coverage/lib/coverage-map.js:25:19
          at Array.forEach (<anonymous>)
      at loadMap (../node_modules/istanbul-lib-coverage/lib/coverage-map.js:24:28)
      at new CoverageMap (../node_modules/istanbul-lib-coverage/lib/coverage-map.js:42:25)
      at maybeConstruct (../node_modules/istanbul-lib-coverage/lib/coverage-map.js:15:12)
```

**Comment by 0xBigBoss** [comment]
> I had the same `Error: Invalid file coverage object, missing keys, found:data` error and fixed it by patching `istanbul-lib-coverage`.
> 
> ```diff
> diff --git a/node_modules/istanbul-lib-coverage/lib/file-coverage.js b/node_modules/istanbul-lib-coverage/lib/file-coverage.js
> index 4ed4c09..08e272c 100644
> --- a/node_modules/istanbul-lib-coverage/lib/file-coverage.js
> +++ b/node_modules/istanbul-lib-coverage/lib/file-coverage.js
> @@ -206,6 +206,8 @@ class FileCoverage {
>              this.data = emptyCoverage(pathOrObj, reportLogic);
>          } else if (pathOrObj instanceof FileCoverage) {
>              this.data = pathOrObj.data;
> +        } else if (typeof pathOrObj === 'object' && pathOrObj.data) {
> +            this.data = pathOrObj.data;
>          } else if (typeof pathOrObj === 'object') {
>              this.data = pathOrObj;
>          } else {
> ```
> 
> The underlying issue is that `FileCoverage` is receiving an instance of `CoverageMap` when it's expecting instance of `FileCoverage` in the constructor branching assignment to `this.data`.
> 
> https://github.com/istanbuljs/istanbuljs/blob/5584b50305a6a17d3573aea25c84e254d4a08b65/packages/istanbul-lib-coverage/lib/file-coverage.js#L205-L213

This patch is working for me now. 

Side not, this seems it's also being tracked in the `nyc` github. https://github.com/istanbuljs/nyc/issues/1226

**Comment by jgnieuwhof** [comment]
@ilijaNL 

> ... Somehow when we use the nyc-test-coverage package, the coverage is not merged correctly and we get really weird code coverage report. I assume this is due that the final sourcemaps are different between what ts-jest transforms and webpack (used by temporal sdk). This is kind of deal breaker atm.

I found the same thing - I was getting coverage but the lines didn't make sense, and were actually inconsistent depending on which test files I included in the test run. The issue does appear to be with how the `mergeIntoGlobalCoverage` function performs its merge, as coverage is correct when bypassing the merge and just writing the coverage data to `.nyc_output`.

Here's the workaround that solved the issue for me:

```typescript

// instead of this
afterAll(async () => {
  workflowCoverage.mergeIntoGlobalCoverage();
});

// do this
import { createCoverageMap } from "istanbul-lib-coverage";

afterAll(async () => {
  const coverageMap = createCoverageMap();
  for (const data of workflowCoverage.coverageMapsData) {
    coverageMap.merge(data);
  }
  await fs.writeFile(
    path.join(".nyc_output", `${uuid4()}.json`),
    JSON.stringify(coverageMap)
  );
});
```

**Comment by ilijaNL** [comment]
> @ilijaNL
> 
> > ... Somehow when we use the nyc-test-coverage package, the coverage is not merged correctly and we get really weird code coverage report. I assume this is due that the final sourcemaps are different between what ts-jest transforms and webpack (used by temporal sdk). This is kind of deal breaker atm.
> 
> I found the same thing - I was getting coverage but the lines didn't make sense, and were actually inconsistent depending on which test files I included in the test run. The issue does appear to be with how the `mergeIntoGlobalCoverage` function performs its merge, as coverage is correct when bypassing the merge and just writing the coverage data to `.nyc_output`.
> 
> Here's the workaround that solved the issue for me:
> 
> ```ts
> // instead of this
> afterAll(async () => {
>   workflowCoverage.mergeIntoGlobalCoverage();
> });
> 
> // do this
> import { createCoverageMap } from "istanbul-lib-coverage";
> 
> afterAll(async () => {
>   const coverageMap = createCoverageMap();
>   for (const data of workflowCoverage.coverageMapsData) {
>     coverageMap.merge(data);
>   }
>   await fs.writeFile(
>     path.join(".nyc_output", `${uuid4()}.json`),
>     JSON.stringify(coverageMap)
>   );
> });
> ```

This is okaay if your whole describe block only include workflow tests, if it includes some non workflow test, jest (global.__coverage__) will not include those in the coverage.

**Comment by diephil** [comment]
Hi there, is there any progress on this topic? We're using jest with @temporalio/nyc-test-coverage@1.11.7 and we are facing the `Error: Invalid file coverage object, missing keys, found:data` issue as well.
