### ISSUE TITLE
[Feature Request] Run temporal worker in bun

### ISSUE THREAD

**Issue by Code2Life** [temporalio/sdk-typescript#1334]
### Bun worker can not work Issue

I tried to use bun as temporal worker, when running temporal client it looked perfect, the workflow created with HTTP2+gRPC, which just supported in bun.js last month.

But when I ran temporal worker it can not work, even bun.sh had implement v8 compatible vm context sandbox. Firstly I found this issue:
![image](https://github.com/temporalio/sdk-typescript/assets/14833440/9bae6fe2-28bc-4587-beb5-196f5dfdaabb)

Then, i tried to comment out the createHook code block, this error disappeared, but the core-bridge was broken

```
2024-01-10T08:41:16.131Z [INFO] webpack 5.89.0 compiled successfully in 486 ms
2024-01-10T08:41:16.132Z [INFO] Workflow bundle created { size: '0.74MB' }
2024-01-10T08:41:16.284520Z  INFO temporal_sdk_core::worker: Initializing worker task_queue=hello-world namespace=default
thread '<unnamed>' panicked at 'Hash table capacity overflow', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.13.2/src/raw/mod.rs:90:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-01-10T08:41:16.286Z [INFO] Worker state changed { state: 'RUNNING' }
2024-01-10T08:41:16.290075Z  INFO next_workflow_activation: temporal_sdk_core::worker: Initiated shutdown task_queue=hello-world namespace=default task_queue=hello-world
2024-01-10T08:41:16.291Z [INFO] Worker state changed { state: 'DRAINED' }
2024-01-10T08:41:16.291Z [INFO] Worker state changed { state: 'STOPPED' }
thread 'core' panicked at 'Workflow processing terminates cleanly: Error joining workflow processing thread: Ok("Hash table capacity overflow")', sdk-core/core/src/worker/mod.rs:409:14
 96 |         }
 97 |         this.shutDownRequested = true;
 98 |         await this.send({ type: 'destroy' });
 99 |         const exitCode = await this.workerThread.terminate();
100 |         if (exitCode !== exports.TERMINATED_EXIT_CODE) {
101 |             throw new core_bridge_1.UnexpectedError(`Failed to terminate Worker thread, exit code: ${exitCode}`);
                                      ^
```

### Additional context

Both Temporal and bun are really amazing. Since bun provide many out-of-box features and better performance than node.js, It would be great if temporal sdk can support bun worker.

**Comment by izakfilmalter** [comment]
Would love to use bun instead!!!!

**Comment by bergundy** [comment]
We know what we need to do to get the SDK working on bun but it'll be a significant lift and may not be prioritized just yet.

**Comment by bergundy** [comment]
I too hope we will support more JS runtimes including bun and deno.

**Comment by brettgoulder** [comment]
nodejs recommends [against using createHook](https://nodejs.org/api/async_hooks.html#async-hooks):

[Stability: 1](https://nodejs.org/api/documentation.html#stability-index) - Experimental. Please migrate away from this API, if you can. We do not recommend using the [createHook](https://nodejs.org/api/async_hooks.html#async_hookscreatehookcallbacks), [AsyncHook](https://nodejs.org/api/async_hooks.html#class-asynchook), and [executionAsyncResource](https://nodejs.org/api/async_hooks.html#async_hooksexecutionasyncresource) APIs as they have usability issues, safety risks, and performance implications. Async context tracking use cases are better served by the stable [AsyncLocalStorage](https://nodejs.org/api/async_context.html#class-asynclocalstorage) API. If you have a use case for createHook, AsyncHook, or executionAsyncResource beyond the context tracking need solved by [AsyncLocalStorage](https://nodejs.org/api/async_context.html#class-asynclocalstorage) or diagnostics data currently provided by [Diagnostics Channel](https://nodejs.org/api/diagnostics_channel.html), please open an issue at https://github.com/nodejs/node/issues describing your use case so we can create a more purpose-focused API.

**Comment by bergundy** [comment]
The SDK uses v8 promise hooks `createHook`, not async hooks.
We need this functionality for showing workflow stack traces.

**Comment by loicnestler** [comment]
Any updates on this? 👀

**Comment by maurovanetti** [comment]
In case you wondered: No, Bun 1.1.0 (out since Monday) does not support Temporal yet. :disappointed: 

```
error: node:v8 createHook is not yet implemented in Bun.
      at new NotImplementedError (internal:shared:20:28)
      at internal:shared:3:70
      at node:v8:3:46
      at node:v8:77:30
      at setPromiseHook (/home/mauro/Codice/in4matic/bun/temporal/node_modules/@temporalio/worker/lib/workflow/vm-shared.js:208:33)
      at install (/home/mauro/Codice/in4matic/bun/temporal/node_modules/@temporalio/worker/lib/workflow/vm-shared.js:140:13)
      at /home/mauro/Codice/in4matic/bun/temporal/node_modules/@temporalio/worker/lib/workflow/reusable-vm.js:139:8
      at create (/home/mauro/Codice/in4matic/bun/temporal/node_modules/@temporalio/worker/lib/workflow/reusable-vm.js:138:21)
      at /home/mauro/Codice/in4matic/bun/temporal/node_modules/@temporalio/worker/lib/workflow/workflow-worker-thread.js:10:36
      at handleRequest (/home/mauro/Codice/in4matic/bun/temporal/node_modules/@temporalio/worker/lib/workflow/workflow-worker-thread.js:6:35)
```

**Comment by hscj87** [comment]
> nodejs recommends [against using createHook](https://nodejs.org/api/async_hooks.html#async-hooks):
> 
> [Stability: 1](https://nodejs.org/api/documentation.html#stability-index) - Experimental. Please migrate away from this API, if you can. We do not recommend using the [createHook](https://nodejs.org/api/async_hooks.html#async_hookscreatehookcallbacks), [AsyncHook](https://nodejs.org/api/async_hooks.html#class-asynchook), and [executionAsyncResource](https://nodejs.org/api/async_hooks.html#async_hooksexecutionasyncresource) APIs as they have usability issues, safety risks, and performance implications. Async context tracking use cases are better served by the stable [AsyncLocalStorage](https://nodejs.org/api/async_context.html#class-asynclocalstorage) API. If you have a use case for createHook, AsyncHook, or executionAsyncResource beyond the context tracking need solved by [AsyncLocalStorage](https://nodejs.org/api/async_context.html#class-asynclocalstorage) or diagnostics data currently provided by [Diagnostics Channel](https://nodejs.org/api/diagnostics_channel.html), please open an issue at https://github.com/nodejs/node/issues describing your use case so we can create a more purpose-focused API.

How to disable using createHook to avoid this error?

**Comment by axe-me** [comment]
it would be great to be able to run temporal worker with bun!

**Comment by bergundy** [comment]
We use promise hooks to capture stack traces that are used in the stack trace query feature that gives visibility into where your workflow is blocked at any given point.

**Comment by zammitjames** [comment]
+1 - not supporting bun has forced us to look elsewhere.

**Comment by maurovanetti** [comment]
**Bun 1.2** is out today. Finally, they declare support for `http2`!

I'm trying to set up Temporal with Bun 1.2 and it seems to go further than before. I have connected a client to my Temporal server, and started a workflow. Unfortunately, the NativeConnection for the worker is hanging forever, though, with no error raised.

Has anyone managed to go beyond this?

**Comment by cortopy** [comment]
Mine also hangs, although I get to see a very cryptic log entry `error: Error (via napi)`. I assume it's something to do with node api compat, but this just leaves me guessing

**Comment by mjameswh** [comment]
I think the `@temporalio/client` package works fine at this point, though I really have to point out that we do not perform regular testing for that runtime. Using this setup in production would not be advisable.

Regarding Worker support, we certainly hope to get there, but we are not actively working in that direction just now. It is simply too early for that.

For example, the "NativeConnection hanging forever" and "error: Error (via napi)" symptoms mentioned above are due to a difference in [how bun checks the error argument on napi_throw](https://github.com/oven-sh/bun/blob/1fa42d81af0806cf06ca9dc050bf06046c3a4b41/src/bun.js/bindings/napi.cpp#L1644-L1659) vs [what's done in Node](https://github.com/nodejs/node/blob/5fad0b93667ffc6e4def52996b9529ac99b26319/src/js_native_api_v8.cc#L1924-L1934). That breaks the method that [Neon Binding](https://github.com/neon-bindings/neon/blob/7f4feb10631cfd3e654112d42a3b5ed472f851e8/crates/neon/src/sys/no_panic.rs#L135-L137) uses to check either it is safe to call back into the JS environment at that time.

It is not worth fixing that issue in upstream projects just yet. Bun's team is already doing some awesome bug hunting work on their NAPI implementation. See for example https://github.com/oven-sh/bun/pull/14501 and https://github.com/oven-sh/bun/pull/16230. I'd expect a few rounds like these, so let's give them time to complete their efforts first, and then for other key dependencies to stabilize.

**Comment by d2201** [comment]
bump, would love to jump over to Bun with projects, that's the last blocker though 🙈

**Comment by d2201** [comment]
^^^ big tnx to @x04. We're getting further with this.

Running bun on canary does enable the worker, however when a workflow is picked up the following error is thrown:
```
2025-04-26T23:03:11.807Z [ERROR] Failed to process Worklow Activation {
  sdkComponent: 'worker',
  taskQueue: 'hello-world',
  runId: '01967457-2a90-7845-a719-e13197b85375',
  namespace: 'default',
  workflowId: 'test',
  workflowType: 'testWorkflow',
  error: TypeError: undefined is not an object (evaluating 'this.activator.getAndResetSinkCalls')
      at getAndResetSinkCalls (/temporaltest/node_modules/@temporalio/worker/lib/workflow/vm-shared.js:262:21)
      at getAndResetSinkCalls (/temporaltest/node_modules/@temporalio/worker/lib/workflow/vm-shared.js:261:34)
      at handleRequest (/temporaltest/node_modules/@temporalio/worker/lib/workflow/workflow-worker-thread.js:61:42)
      at handleRequest (/temporaltest/node_modules/@temporalio/worker/lib/workflow/workflow-worker-thread.js:23:32)
      at <anonymous> (/temporaltest/node_modules/@temporalio/worker/lib/workflow/workflow-worker-thread.js:92:38)
      at <anonymous> (/temporaltest/node_modules/@temporalio/worker/lib/workflow/workflow-worker-thread.js:90:33),
  workflowExists: true
}
```

**Comment by d2201** [comment]
Adding on top of the previous comment.

I have set up a new project using the [core application docs](https://docs.temporal.io/develop/typescript/core-application#install-a-temporal-sdk)

I used the following command:
```sh
npx @temporalio/create@1.11.7 testbundle -s hello-world --sdk-version 1.11.7 --no-git-init
```

I ran the worker with Bun:
```sh
bun run src/worker.ts
```

And ran the client to initiate a workflow:
```sh
bun run src/client.ts
```

The workflow isn't being picked up by the worker. (it gets assigned, but no actual work is being done).
No errors are visible.

**Comment by d2201** [comment]
Got a little bit further by modifying the `ReusableVMWorkflowCreator.createWorkflow` method (the `setActivatorUntyped` does not always work for some reason - as in: does not set the activator correctly).

Got blocked however at the last final step -> workflow's execution cannot be completed 🤷 -- the logs are silent.
The only suspicion I have is, that there is something wrong within this handler: 
```ts
await this.nativeWorker.completeWorkflowActivation(completion.buffer.slice(completion.byteOffset))
``` 
but I can not easily debug it.

I have also tried with running the latest code (post January's 1.11.7 release), but ended up with the same issues.

Bun version: 1.2.11


![Image](https://github.com/user-attachments/assets/8a78d917-f7c8-4578-a717-7a0f8507014a)

**Comment by mjameswh** [comment]
Thanks a lot @d2201 for all this testing, and thanks @x04 for pushing the NAPI fix to bun!

I unfortunately can't put time investigating this myself just now, but really appreciate the community effort.

@d2201: Regarding your tests above, there are quite a lot of moving parts involved.

To simplify things a bit, I'd suggest trying to add `debugMode: true` to your worker options. That will force the worker into single thread mode (thus avoiding use of the `node:worker_threads` module).

You should set `reuseV8Context: false`, which will force creation of a distinct vm context for each workflow execution. That execution mode is known to be significantly less efficient and increase memory usage (or at least, that's true in Node; I wouldn't be surprised if performance profile turns out to be very different in Bun and Deno), but follow a much simpler execution model that is less likely to trigger edge cases in a "node-compatibility" implementation.

You may also want to experiment with the code on the main branch of the TS SDK repo, rather than the 1.11.8. Several key components of the SDK went through some significant work, including a major refactor of the native bridge layer, and multiple significant fixes in the Worker and Workflow Sandbox. I can't promise that these changes will immediately get us closer to the goal of running a Temporal Worker on Bun, and can't exclude the possibility that they might even add some more challenges due to the use of some additional NAPI features… But I honestly hope that the more robust design and better error handling will make it easier to progress forward.

**Comment by d2201** [comment]
@mjameswh Thank you, for this summary. It helped me a lot.

I think it's not the NAPI issue anymore.

## Environment information

```
SDK (commit: caae0a4eec4ed489c53f102b04f7d4afde318c5b) (1.12.0-rc)
Node v22.4.0
Bun v1.2.15
```

## Investigation results

The debug helped me with understanding what's going on (at least to some degree). It all boils down (in my opinion) to the Bun's compatibility with `node:vm`.

### So what's happening?

There seems to be some sort of race condition happening.

High-level of how Node does the part of completion:
```
- runs `activate` function within the workflow vm context
- workflow gets completed (I've put console.log statements all over the place, and I see the workflow results in there)
- `activate` function ends
- ... bunch of other things in the process run
- the completion is being sent out to the `core` with `successful.commands` containing the `completeWorkflowExecution` command.
```

High-level of how Bun does the part of completion:
```
- runs `activate function withing the workflow vm context
- `activate` function ends
- ... bunch of other things in the process run
- the completion is being sent out to the `core` with `successful.commands` being empty
- I see the console logs from workflow results
```

I am not sure yet how to solve it.

**Comment by mjameswh** [comment]
> ```
> - runs `activate function withing the workflow vm context
> - `activate` function ends
> - ... bunch of other things in the process run
> - the completion is being sent out to the `core` with `successful.commands` being empty
> - I see the console logs from workflow results
> ```

If I understand correctly what you describe, it looks like Bun's `vm` implementation is interleaving microtasks from inside and outside the `vm`.

The JS engine is expected to maintain a distinct event queue for inside the VM, detached from the main event queue. Also, given the `microtaskMode: 'afterEvaluate'` option on `vm.createContext()`, the engine should wait for all microtasks on that inside event task queue to drain before returning from a `vm.runInContext()` call.

**Comment by d2201** [comment]
Yup, I'll try to reproduce this issue in a more controllable environment and will report it to Bun's maintainers.

**Comment by d2201** [comment]
Got it! Reported: https://github.com/oven-sh/bun/issues/20145

**Comment by mjameswh** [comment]
> The JS engine is expected to maintain a distinct event queue for inside the VM, detached from the main event queue. Also, given the microtaskMode: 'afterEvaluate' option on vm.createContext(), the engine should wait for all microtasks on that inside event task queue to drain before returning from a vm.runInContext() call.

By the way, we [used to have a patch](https://github.com/temporalio/sdk-typescript/blob/49c6b1341daef2b94a0a989d515cbf97b8b02fa7/packages/worker/src/workflow/vm-shared.ts#L359-L365) for that, because the `microtaskMode: 'afterEvaluate'` only got added in Node 14.6. It was removed when we stopped maintaining that older release.

You may try to restore that patch and see if that gets you a bit farther.

**Comment by mjameswh** [comment]
> Any chance we can go back to that patch, or should we just wait for bun to fix this incompatibility?

I don't have any objection to reintroduce the patch, but we'll have to think of a good way to conditionally enable or disable it. We previously just checked for Node's release number, but I don't want to rely on that kind of things if the goal is to support multiple JS runtimes.

We'll also need to confirm that all aspects of the sandbox still work correctly with that patch. The sandboxing code has gone through some significant changes since that patch was removed. It is possible that this patch might no longer be reliable.

**Comment by d2201** [comment]
> but its seems only pick up first activity, the rest of activities are not running on bun, tested many many times

@liho00 I didn't test this beyond the `hello world` sample, as it's too unstable to do anything more than that. Once the two runtimes start to behave similarly (without additional flags & custom patches), we can move on to testing other use cases.

> We previously just checked for Node's release number, but I don't want to rely on that kind of things if the goal is to support multiple JS runtimes.

Agreed.

My take is that Bun isn't stable enough for now, and anyone who uses Bun for more than basic CRUD examples knows that. The `node:vm` module is considered stable in Node, so every runtime that tries to be a "drop-in Node replacement" should at least implement all stable APIs from Node.

The patch itself might do more harm than good, and even with it:

>We'll also need to confirm that all aspects of the sandbox still work correctly with that patch. The sandboxing code has gone through some significant changes since that patch was removed. It is possible that this patch might no longer be reliable.

That remains a concern.

After all, I'm just a follower - not sure how important is it to others here - but for me Bun is mostly a convenience rather than a game changer. IMO, there are bigger DX fish to fry in the SDK, and I'd passively wait until Bun catches up. Nevertheless, I'll keep updating here as things progress, so others can have more visibility into the latest state of this issue.

**Comment by nicu-dev** [comment]
yeeeees, can't wait for bun ❤️ temporal

**Comment by zammitjames** [comment]
It's insane that this hasn't been implemented yet.

**Comment by BrianEstrada** [comment]
@hckhanh don't want to promote another service here on Temporal's repo but it's one of the top 4 google search results for `durable workflows`

**Comment by rajasekarshanmugam** [comment]
are there any pointers where to look for the isolate support in temporal..?

**Comment by hckhanh** [comment]
@yordis I afraid that this issue is not one of their priority stuffs. I think you should move away from Temporal just like I did. My suggestion: Restate, Inngest

Both of them support Bun really well

**Comment by slavb18** [comment]
Confirm worker running in 1.15.0. Thank you temporal.io team!
