### ISSUE TITLE
[Bug] Runtime fails to start with OtelCollectorExporter configured

### ISSUE THREAD

**Issue by ksapchuk** [temporalio/sdk-typescript#1342]
### What are you really trying to do?
I updated to the latest typescript SDK 1.9.0 and the worker is failing to start with the `OtelCollectorExporter` settings enabled. 

### Describe the bug
When calling `Runtime.install` the worker crashes with the following error. Passing in an empty `headers` map seems to work but the parameter is labeled optional and was not required in the previous SDK version. 
```
Failed to build otlp exporter options: UninitializedField("headers")
TypeError: Failed to build otlp exporter options: UninitializedField("headers")
     at /Users/kirill/src/sparta/node_modules/@temporalio/core-bridge/index.js:16:14
     at Function.create (/Users/kirill/src/sparta/node_modules/@temporalio/worker/src/runtime.ts:206:31)
     at Function.install (/Users/kirill/src/sparta/node_modules/@temporalio/worker/src/runtime.ts:179:17)
     at runWorker (/Users/kirill/src/sparta/packages/api/src/entrypoints/TemporalWorker.ts:305:11)
     at start (/Users/kirill/src/sparta/packages/api/src/entrypoints/TemporalWorker.ts:517:9)
     at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Minimal Reproduction
This fails
```
  Runtime.install({
    telemetryOptions: {
      metrics: {
        otel: {
          metricsExportInterval: '60s',
          url: 'grpc://0.0.0.0:4316',
        },
      },
    },
  });
```
This works
```
  Runtime.install({
    telemetryOptions: {
      metrics: {
        otel: {
          metricsExportInterval: '60s',
          url: 'grpc://0.0.0.0:4316',
          headers: {}
        },
      },
    },
  });
```

### Environment/Versions
- OS and processor: M1 Mac
- Temporal Version: typescript 1.9.0

**Comment by bergundy** [comment]
Thanks for reporting, this is an easy fix. We should take this on soon @mjameswh.
