### ISSUE TITLE
[Bug] listWorkflowExecutions without namespace throws an exception.

### ISSUE THREAD

**Issue by kakopappa** [temporalio/sdk-typescript#1347]
### What are you really trying to do?

List workflows

```
const response = await connection.workflowService.listWorkflowExecutions({
        query: `WorkflowId = "${history.workflowId}"`, 
});

```
### Describe the bug

List workflows without namespace throw an exception. It needs to be marked as mandatory

```
Error: 3 INVALID_ARGUMENT: Namespace is empty.
    at Object.callErrorFromStatus (\@temporalio\client\node_modules\@grpc\grpc-js\build\src\call.js:31:19)
    at Object.onReceiveStatus (\@temporalio\client\node_modules\@grpc\grpc-js\build\src\client.js:195:52)
    at \@temporalio\client\node_modules\@grpc\grpc-js\build\src\call-stream.js:111:35
    at onReceiveStatus (\@temporalio\client\lib\grpc-retry.js:134:25)
    at Object.onReceiveStatus (\@temporalio\client\lib\grpc-retry.js:137:17)
    at InterceptingListenerImpl.onReceiveStatus (\@temporalio\client\node_modules\@grpc\grpc-js\build\src\call-stream.js:106:23)
    at Object.onReceiveStatus (\@temporalio\client\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:365:141)
    at Object.onReceiveStatus (\@temporalio\client\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:328:181)
    at \@temporalio\client\node_modules\@grpc\grpc-js\build\src\call-stream.js:188:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (\@temporalio\client\node_modules\@grpc\grpc-js\build\src\client.js:163:34)
    at Service.rpcImpl (\@temporalio\client\lib\connection.js:216:33)
    at Service.rpcCall (\@temporalio\proto\node_modules\protobufjs\src\rpc\service.js:94:21)
    at executor (\@protobufjs\aspromise\index.js:44:16)
    at new Promise (<anonymous>)
    at Object.asPromise (\@protobufjs\aspromise\index.js:28:12)
    at Service.rpcCall (\@temporalio\proto\node_modules\protobufjs\src\rpc\service.js:86:21)
    at Service.listWorkflowExecutions (eval at Codegen (\@protobufjs\codegen\index.js:50:33), <anonymous>:4:15)
    at deleteTemporal (D:\MyProjects\sinric_pro\server\server\services\automation.service.js:99:57)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 3,
  details: 'Namespace is empty.',
  metadata: Metadata {
    internalRepr: Map(1) { 'content-type' => [Array] },
    options: {}
  }
}
```

![image](https://github.com/temporalio/sdk-typescript/assets/7474406/5503f629-e0b9-4c6d-80e5-3d6e4307b74f)

mus be

```
 const response = await connection.workflowService.listWorkflowExecutions({
        namespace: 'default',
        query: `WorkflowId = "${history.workflowId}"`, 
});
```

Using

 "@temporalio/activity": "^1.9.0",
 "@temporalio/client": "^1.9.0",
 "@temporalio/worker": "^1.9.0",
 "@temporalio/workflow": "^1.9.0",

**Comment by mjameswh** [comment]
`connection.workflowService.*` is the low level gRPC API. Files there gets automatically generated from our [protobuf definitions](https://github.com/temporalio/api). Unfortunately, there is no way to have that generator mark required properties as non-optional (actually, the notion of a "required" property, as in "it must be defined by the caller", doesn't even exist in protobuf 3).

I strongly recommend you use [client.workflow.list](https://typescript.temporal.io/api/classes/client.WorkflowClient#list) instead, which is the high level API to list workflows. It provides a more intuitive API, and handle pagination internally.
