### ISSUE TITLE
[Bug] crypto.getRandomValues not supported

### ISSUE THREAD

**Issue by acheong08** [temporalio/sdk-typescript#1390]
### What are you really trying to do?

Use [uuid](https://www.npmjs.com/package/uuid)

### Describe the bug

```ts
2024-04-08T08:27:14.376Z [WARN] Workflow failed {
  namespace: 'default',
  taskQueue: 'hello-world',
  workflowId: 'my-workflow',
  runId: 'b769edf1-a169-4eaa-9a8b-ab3a397dc162',
  workflowType: 'engine',
  error: Error: crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported
      at rng (/home/acheong/Projects/skand/v2/engine/node_modules/uuid/dist/esm-browser/rng.js:13:0)
      at v4 (/home/acheong/Projects/skand/v2/engine/node_modules/uuid/dist/esm-browser/v4.js:11:52)
      at v4 (/home/acheong/Projects/skand/v2/engine/src/lib/engine.ts:128:19)
      at nanoid (/home/acheong/Projects/skand/v2/engine/src/lib/engine.ts:227:33)
      at executeNodes (/home/acheong/Projects/skand/v2/engine/src/lib/engine.ts:88:32)
      at run (/home/acheong/Projects/skand/v2/engine/src/workflows.ts:28:24)
      at Activator.startWorkflowNextHandler (/home/acheong/Projects/skand/v2/engine/node_modules/@temporalio/workflow/src/internals.ts:410:16)
      at /home/acheong/Projects/skand/v2/engine/node_modules/@temporalio/workflow/src/internals.ts:428:8
      at executeWithLifecycleLogging (/home/acheong/Projects/skand/v2/engine/node_modules/@temporalio/workflow/src/logs.ts:80:12)
      at Activator.startWorkflow (/home/acheong/Projects/skand/v2/engine/node_modules/@temporalio/workflow/src/internals.ts:427:34)
}
```

### Minimal Reproduction

https://github.com/acheong08/temporal-crypto-error/

### Environment/Versions

- OS and processor: [e.g. M1 Mac, x86 Windows, Linux]
- Temporal Version: 1.9.3
- Are you using Docker or Kubernetes or building Temporal from source? No

**Comment by mjameswh** [comment]
By design, UUIDv4 requires a random number generator, and the NPM `uuid` package uses the built-in `crypto` module's `getRandomValues` function for that purpose. But the built-in `crypto` module can't be imported from workflow code because it has non-deterministic behavior.

Workflow code [must be deterministic](https://docs.temporal.io/workflows#deterministic-constraints).

You have two easy options to resolves this:
1. If only care about generating some UUID, uses the `uuid4` function exported by the `@temporalio/workflow` package. That implementation internally uses a replay-safe random number generator.
2. As a more general solution, non-deterministic logic should usually be moved to Activities instead. Activities have no need to be deterministic.

You have two options:
1. If you simply need to generate a UUID,

**Comment by mjameswh** [comment]
On a side note, I'm a bit puzzled by the fact that the dependency to the `crypto` module didn't get caught by the Workflow Bundler, which would have provided a more suitable error message.

I noticed the presence of a `bun.lockb` file in your repro code. Have you tried running this with Bun? Unfortunately, Node.js is the only supported JS runtime at this moment, and I honestly don't think that compatibility layers provided by alternate JS offerings will be able to reliably execute the Workflow Sandboxing engine at this time.

But if you got some success with this, I'd be interested to know more.

**Comment by acheong08** [comment]
> On a side note, I'm a bit puzzled by the fact that the dependency to the crypto module didn't get caught by the Workflow Bundler, which would have provided a more suitable error message.

That would be helpful indeed.
