### ISSUE TITLE
[Bug] Package initializer does not work for some users

### ISSUE THREAD

**Issue by sw-yx** [temporalio/sdk-typescript#333]
### Describe the bug

https://temporalio.slack.com/archives/C01DKSMU94L/p1634944174028300

### To Reproduce

i could reproduce (on both node 14 and 16) with

```
 npx @temporalio/create@latest moop
✔ Which sample would you like to use? › hello-world
Creating a new Temporal project in /Users/swyx/Temporal/testnodesdk/moop/

✔ Directory /Users/swyx/Temporal/testnodesdk/moop/ already exists. Would you like to replace it? … yes
Downloading files for sample hello-world. This might take a moment.

Installing packages. This might take a couple of minutes.

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/swyx/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/swyx/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/swyx/.npm/_logs/2021-10-24T10_08_05_549Z-debug.log

Aborting installation.
  npm has failed.
```

notice that my error shows a different root than Ramazan's:

```
ramazanozer@Ramazans-MBP-39 alphademov2 % npx @temporalio/create@latest
✔ What is your project named? … my-temporal
✔ Which sample would you like to use? › hello-world
Creating a new Temporal project in /Users/ramazanozer/IdeaProjects/alphademov2/my-temporal/

Downloading files for sample hello-world. This might take a moment.

Installing packages. This might take a couple of minutes.


Aborting installation.
Unexpected error. Please report it as a bug:
Error: ENOENT: no such file or directory, open '/Users/ramazanozer/IdeaProjects/alphademov2/my-temporal/package.json'
    at Object.openSync (fs.js:497:3)
    at readFileSync (fs.js:393:35)
    at updateNodeVersion (/Users/ramazanozer/.npm/_npx/84edb3507a773a27/node_modules/@temporalio/create/lib/helpers/install.js:32:52)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async createApp (/Users/ramazanozer/.npm/_npx/84edb3507a773a27/node_modules/@temporalio/create/lib/create-project.js:141:5)
    at async start (/Users/ramazanozer/.npm/_npx/84edb3507a773a27/node_modules/@temporalio/create/lib/index.js:126:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/ramazanozer/IdeaProjects/alphademov2/my-temporal/package.json'
}
```

### Context

i think https://github.com/temporalio/sdk-typescript/blob/4f4e3f6fc03abe928fae1f3f2459b2b256ed3017/packages/create-project/src/helpers/install.ts#L44 needs better error handling - readFileSync is just too error prone.

but the root cause is not the file read, it is the lack of package.json in the cloned folder.

**Comment by bergundy** [comment]
@lorensr could you please make the script fail more gracefully in the case of sample not found?

**Comment by lorensr** [comment]
Here's what we print when the provided repo doesn't have a `package.json`:

```
$ npx @temporalio/create@latest t2 -s https://github.com/lorensr/food-delivery/tree/main/components
Error: Could not locate a package.json at "https://api.github.com/repos/lorensr/food-delivery/contents/components/package.json?ref=main".
Please check that the repository is a Temporal TypeScript SDK template and try again.
```

I can add a check that covers when the provided repo has changed names/orgs.

Here's what we print when a chosen sample doesn't have a `package.json`:

![image](https://user-images.githubusercontent.com/251288/139513619-6fa78b83-a48c-47e1-a7fd-085e5df9a807.png)

I'll also have it print a list of samples and link to samples-typescript.
