### ISSUE TITLE
[Feature Request] Better context for grpc errors in client

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-typescript#365]
Right now client errors are thrown by grpc-js asynchronously and the stack trace is meaningless.
We should catch errors from WorkflowClient methods and rethrow to provide better context.

**Comment by lorensr** [comment]
A couple of examples:

- `DEADLINE_EXCEEDED` in #376
- `NOT_FOUND`: calling methods on a nonexistent-workflowID handle:

```js
  const handle = client.getHandle('nonexistent');
  await handle.result();
```

```
Error: 5 NOT_FOUND: sql: no rows in result set
    at Object.callErrorFromStatus (/Users/me/gh/samples-typescript/hello-world/node_modules/@grpc/grpc-js/src/call.ts:81:24)
    at Object.onReceiveStatus (/Users/me/gh/samples-typescript/hello-world/node_modules/@grpc/grpc-js/src/client.ts:343:36)
    at /Users/me/gh/samples-typescript/hello-world/node_modules/@grpc/grpc-js/src/call-stream.ts:182:27
    at Object.onReceiveStatus (/Users/me/gh/samples-typescript/hello-world/node_modules/@temporalio/client/src/grpc-retry.ts:106:15)
    at InterceptingListenerImpl.onReceiveStatus (/Users/me/gh/samples-typescript/hello-world/node_modules/@grpc/grpc-js/src/call-stream.ts:178:19)
    at Object.onReceiveStatus (/Users/me/gh/samples-typescript/hello-world/node_modules/@grpc/grpc-js/src/client-interceptors.ts:430:34)
    at Object.onReceiveStatus (/Users/me/gh/samples-typescript/hello-world/node_modules/@grpc/grpc-js/src/client-interceptors.ts:392:48)
    at /Users/me/gh/samples-typescript/hello-world/node_modules/@grpc/grpc-js/src/call-stream.ts:299:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 5,
  details: 'sql: no rows in result set',
  metadata: Metadata {
    internalRepr: Map(2) {
      'content-type' => [Array],
      'grpc-status-details-bin' => [Array]
    },
    options: {}
  }
}
```

**Comment by Sushisource** [comment]
The not found one needs to be fixed server side - but both calls should have a more meaningful callstack.

**Comment by iamnafets** [comment]
I'm still getting "sql: no rows in result set" in error messages. Unfortunately it gives me no leads to debug.
