### ISSUE TITLE
[Bug] Poor error message running sleep() in a Node script

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [temporalio/sdk-typescript#406]
### To Reproduce

Run `node` on a file with these contents:

```
import { sleep } from "@temporalio/workflow";

await sleep("100 ms");
```

### Expected behavior

An error message something like:

```
Workflow commands may only be run from within a workflow.
```

### Screenshots/Terminal output

```
/mnt/c/Code/temporal-slack-adventure-bot-2/node_modules/@temporalio/workflow/lib/cancellation-scope.js:117
        return exports.storage.getStore() ?? exports.ROOT_SCOPE;
                               ^

TypeError: exports.storage.getStore is not a function
    at Function.current (/mnt/c/Code/temporal-slack-adventure-bot-2/node_modules/@temporalio/workflow/lib/cancellation-scope.js:117:32)
    at /mnt/c/Code/temporal-slack-adventure-bot-2/node_modules/@temporalio/workflow/lib/workflow.js:28:62
    at new Promise (<anonymous>)
    at timerNextHandler (/mnt/c/Code/temporal-slack-adventure-bot-2/node_modules/@temporalio/workflow/lib/workflow.js:27:12)
    at sleep (/mnt/c/Code/temporal-slack-adventure-bot-2/node_modules/@temporalio/workflow/lib/workflow.js:70:12)
    at file:///mnt/c/Code/temporal-slack-adventure-bot-2/src/repro.mjs:3:7
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
```

### Versions

- OS: [e.g. Mac, Windows, Linux]: WSL 2.0 Ubuntu
- Temporal Version 0.16.x of the TypeScript SDK
- Are you using Docker or Kubernetes or building Temporal from source?: Docker

**Comment by lorensr** [comment]
> Workflow commands may only be run from within a workflow.

I like it—sounds like a helpful message to see for all `@temporal/workflow` exports used outside of an isolate. Maybe:

Error: This function is meant to be used inside Workflow code. Workflow code should only be run by the Worker (and is provided to the Worker via either the `workflowsPath` or `workflowBundle` option).

**Comment by mjameswh** [comment]
Closing in favor of #553.
