### ISSUE TITLE
[Bug] Fix flakey tests

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#496]
There are a number of transient CI failures that we'd like to fix with code instead of the "rebuild" button 😄 Let's collect them.

Here's one:

https://github.com/temporalio/sdk-typescript/runs/5296245052?check_suite_focus=true

```
Run node scripts/init-from-verdaccio.js --registry-dir /tmp/registry --sample https://github.com/temporalio/samples-typescript/tree/next/hello-world-mtls
Starting local registry
Error: Path D:\tmp\registry\verdaccio.log does not exist
```

[compile-binaries (macos-latest, x86_64-apple-darwin)](https://github.com/temporalio/sdk-typescript/runs/5631928072?check_suite_focus=true#logs)

```
Warning, failed destroying registry ChildProcessError: Process failed
    at ChildProcess.<anonymous> (/Users/runner/work/sdk-typescript/sdk-typescript/scripts/utils.js:18:[16](https://github.com/temporalio/sdk-typescript/runs/5631928072?check_suite_focus=true#step:10:16))
    at ChildProcess.emit (node:events:5[20](https://github.com/temporalio/sdk-typescript/runs/5631928072?check_suite_focus=true#step:10:20):28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  code: 1,
  signal: null
}
Error: Path /tmp/registry/verdaccio.log does not exist
```

**Comment by lorensr** [comment]
```
Run node scripts/publish-to-verdaccio.js --registry-dir /tmp/registry
Starting local registry
Error: Timed out waiting for verdaccio - {"level":40,"time":1645592119724,"pid":3384,"hostname":"fv-az140-199","content":"htpasswd","prefix":"verdaccio","msg":"Plugin successfully loaded: @{prefix}-@{content}"}
{"level":40,"time":1645592119745,"pid":3384,"hostname":"fv-az140-199","addr":"http://localhost:4873/","version":"verdaccio/5.6.0","msg":"http address - @{addr} - @{version}"}

    at Timeout._onTimeout (D:\a\sdk-typescript\sdk-typescript\scripts\registry.js:59:18)
Error: Process completed with exit code 1.
```

https://github.com/temporalio/sdk-typescript/runs/5298726692?check_suite_focus=true

**Comment by lorensr** [comment]
[sdk-features-tests / build-ts](https://github.com/temporalio/sdk-typescript/runs/5298947280?check_suite_focus=true#logs) > Checkout typescript SDK repo

```
34s
Run actions/checkout@v2
Syncing repository: temporalio/sdk-typescript
Getting Git version info
Initializing the repository
Disabling automatic garbage collection
Setting up auth
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=[1](https://github.com/temporalio/sdk-typescript/runs/5298947280?check_suite_focus=true#step:4:1) origin +refs/heads/remove-comments*:refs/remotes/origin/remove-comments* +refs/tags/remove-comments*:refs/tags/remove-comments*
  The process '/usr/bin/git' failed with exit code 1
  Waiting [18](https://github.com/temporalio/sdk-typescript/runs/5298947280?check_suite_focus=true#step:4:18) seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/remove-comments*:refs/remotes/origin/remove-comments* +refs/tags/remove-comments*:refs/tags/remove-comments*
  The process '/usr/bin/git' failed with exit code 1
  Waiting 15 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/remove-comments*:refs/remotes/origin/remove-comments* +refs/tags/remove-comments*:refs/tags/remove-comments*
  Error: The process '/usr/bin/git' failed with exit code 1
```

**Comment by lorensr** [comment]
[test-npm-init (windows-latest, x86_64-pc-windows-msvc, 16, cloud, hello-world-mtls)](https://github.com/temporalio/sdk-typescript/runs/5399993983?check_suite_focus=true#logs)

```
Run node scripts/test-example.js --work-dir /tmp/registry/example
Starting worker
WorkflowExecutionAlreadyStartedError: Workflow execution already started
    at WorkflowClient._startWorkflowHandler (D:\tmp\registry\example\node_modules\@temporalio\client\src\workflow-client.ts:659:[15](https://github.com/temporalio/sdk-typescript/runs/5399993983?check_suite_focus=true#step:12:15))
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WorkflowClient.execute (D:\tmp\registry\example\node_modules\@temporalio\client\src\workflow-client.ts:378:5)
    at async run (D:\tmp\registry\example\src\execute-workflow.ts:38:[18](https://github.com/temporalio/sdk-typescript/runs/5399993983?check_suite_focus=true#step:12:18)) {
  workflowId: 'my-business-id',
  workflowType: 'example'
}
```

**Comment by lorensr** [comment]
Buildkite https://buildkite.com/temporal/typescript-sdk/builds/785#a8a253f2-23f1-407b-b9b6-35daac9a835e

![image](https://user-images.githubusercontent.com/251288/157141914-8b8eb1d5-79e0-4b61-8768-75f945749b10.png)

**Comment by lorensr** [comment]
[test-npm-init (ubuntu-latest, x86_64-unknown-linux-gnu, 16, local, hello-world)](https://github.com/temporalio/sdk-typescript/runs/5504329163?check_suite_focus=true#logs) 

hanging, perhaps due to a failed attempt at GH canceling it because another test failed? 

<img width="894" alt="image" src="https://user-images.githubusercontent.com/251288/157784306-606f7093-931e-4021-a764-abe2984293a8.png">

Thanks to @julianocomg for reporting

**Comment by lorensr** [comment]
[build-and-test (14, macos-latest)](https://github.com/temporalio/sdk-typescript/runs/5631927497?check_suite_focus=true#logs)

```
@temporalio/test: npm ERR! code ELIFECYCLE
@temporalio/test:   ✔ workflows › nestedCancellation (607ms)
@temporalio/test: npm ERR! errno 1
@temporalio/test:   ✔ workflows › partialShield (600ms)
@temporalio/test: npm ERR! @temporalio/test@0.19.1 test: `ava ./lib/test-*.js`
@temporalio/test:   ─
@temporalio/test: npm ERR! Exit status 1
@temporalio/test:   testenvironment › before hook
@temporalio/test: npm ERR! 
@temporalio/test:   Rejected promise returned by test. Reason:
@temporalio/test: npm ERR! Failed at the @temporalio/test@0.19.1 test script.
@temporalio/test:   Error {
@temporalio/test: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
@temporalio/test:     message: 'Failed to connect before the deadline',
@temporalio/test:   }
@temporalio/test:   › checkState (/Users/runner/work/sdk-typescript/sdk-typescript/node_modules/@grpc/grpc-js/src/client.ts:172:18)
@temporalio/test:   › Timeout._onTimeout (/Users/runner/work/sdk-typescript/sdk-typescript/node_modules/@grpc/grpc-js/src/channel.ts:712:9)
@temporalio/test:   ─
@temporalio/test:   1 hook failed
@temporalio/test: npm WARN Local package.json exists, but node_modules missing, did you mean to install?
@temporalio/test: npm ERR! A complete log of this run can be found in:
@temporalio/test: npm ERR!     /Users/runner/.npm/_logs/2022-03-21T18_00_02_510Z-debug.log
lerna ERR! npm run test exited 1 in '@temporalio/test'
npm ERR! Test failed.  See above for more details.
Error: Process completed with exit code 1.
```

**Comment by lorensr** [comment]
[build-and-test (16, ubuntu-latest)](https://github.com/temporalio/sdk-typescript/runs/5635846701?check_suite_focus=true#logs)

```
Run npm run wait-namespace

> wait-namespace
> node ./scripts/wait-on-temporal.mjs

Failed to connect Error: 1[4](https://github.com/temporalio/sdk-typescript/runs/5635846701?check_suite_focus=true#step:11:4) UNAVAILABLE: No connection established
    at Object.callErrorFromStatus (/home/runner/work/sdk-typescript/sdk-typescript/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/home/runner/work/sdk-typescript/sdk-typescript/node_modules/@grpc/grpc-js/build/src/client.js:180:[5](https://github.com/temporalio/sdk-typescript/runs/5635846701?check_suite_focus=true#step:11:5)2)
    at /home/runner/work/sdk-typescript/sdk-typescript/node_modules/@grpc/grpc-js/build/src/call-stream.js:111:35
    at Object.onReceiveStatus (/home/runner/work/sdk-typescript/sdk-typescript/packages/client/lib/grpc-retry.js:89:37)
    at Object.onReceiveStatus (/home/runner/work/sdk-typescript/sdk-typescript/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:3[6](https://github.com/temporalio/sdk-typescript/runs/5635846701?check_suite_focus=true#step:11:6)5:141)
    at Object.onReceiveStatus (/home/runner/work/sdk-typescript/sdk-typescript/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /home/runner/work/sdk-typescript/sdk-typescript/node_modules/@grpc/grpc-js/build/src/call-stream.js:182:[7](https://github.com/temporalio/sdk-typescript/runs/5635846701?check_suite_focus=true#step:11:7)[8](https://github.com/temporalio/sdk-typescript/runs/5635846701?check_suite_focus=true#step:11:8)
    at processTicksAndRejections (node:internal/process/task_queues:78:[11](https://github.com/temporalio/sdk-typescript/runs/5635846701?check_suite_focus=true#step:11:11)) {
  code: [14](https://github.com/temporalio/sdk-typescript/runs/5635846701?check_suite_focus=true#step:11:14),
  details: 'No connection established',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
Error: Process completed with exit code 1.
```

**Comment by lorensr** [comment]
This one was local:

```
@temporalio/test:   local-activities › Local activity backs off with timer
@temporalio/test:   Difference:
@temporalio/test:   - 0
@temporalio/test:   + 1
@temporalio/test:   › src/test-local-activities.ts:236:9
@temporalio/test:   › runWorker (src/test-local-activities.ts:21:3)
@temporalio/test:   › src/test-local-activities.ts:222:5
```

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/251288/170603741-b801dbab-82fa-49bf-a8c6-fafe7074bacc.png">

**Comment by lorensr** [comment]
[build-and-test (14, windows-latest)](https://github.com/temporalio/sdk-typescript/runs/6820063801?check_suite_focus=true#logs)

```
@temporalio/test:   testenvironment » TestEnvironment can toggle between normal and skipped time
@temporalio/test:   Rejected promise returned by test. Reason:
@temporalio/test:   UnexpectedError {
@temporalio/test:     message: 'Found more than one reference to the native Worker',
@temporalio/test:   }
@temporalio/test:   » Runtime.deregisterWorker (D:/a/sdk-typescript/sdk-typescript/packages/worker/src/runtime.ts:310:51)
@temporalio/test:   » NativeWorker.finalizeShutdown (D:/a/sdk-typescript/sdk-typescript/packages/worker/src/worker.ts:178:24)
@temporalio/test:   » Worker.run (D:/a/sdk-typescript/sdk-typescript/packages/worker/src/worker.ts:1485:31)
@temporalio/test:   » withWorker (src/test-testenvironment.ts:26:20)
@temporalio/test:   » src/test-testenvironment.ts:90:3
@temporalio/test:   testenvironment » after.always hook
@temporalio/test:   Rejected promise returned by test. Reason:
@temporalio/test:   IllegalStateError {
@temporalio/test:     message: 'Cannot close connection while Workers hold a reference to it',
@temporalio/test:   }
@temporalio/test:   » NativeConnection.close (D:/a/sdk-typescript/sdk-typescript/packages/worker/src/connection.ts:51:13)
@temporalio/test:   » TestWorkflowEnvironment.teardown (D:/a/sdk-typescript/sdk-typescript/packages/testing/src/index.ts:240:33)
@temporalio/test:   » src/test-testenvironment.ts:43:3
@temporalio/test:   ─
@temporalio/test:   1 hook failed
@temporalio/test:   1 test failed
```

**Comment by bergundy** [comment]
Just fixed the latest one in #701

**Comment by lorensr** [comment]
[build-and-test (14, macos-latest)](https://github.com/temporalio/sdk-typescript/runs/7048994137?check_suite_focus=true#logs)

```
Run npm ci --ignore-scripts
  npm ci --ignore-scripts
  shell: /bin/bash -e {0}
  env:
    GITHUB_TOKEN: ***
npm ERR! cb() never called!
npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/runner/.npm/_logs/[2](https://github.com/temporalio/sdk-typescript/runs/7048994137?check_suite_focus=true#step:6:2)022-06-2[4](https://github.com/temporalio/sdk-typescript/runs/7048994137?check_suite_focus=true#step:6:4)T21_42_[5](https://github.com/temporalio/sdk-typescript/runs/7048994137?check_suite_focus=true#step:6:5)0_24[8](https://github.com/temporalio/sdk-typescript/runs/7048994137?check_suite_focus=true#step:6:9)Z-debug.log
Error: Process completed with exit code 1.
```

**Comment by lorensr** [comment]
[build-and-test (16, macos-latest)](https://github.com/temporalio/sdk-typescript/runs/7201322718?check_suite_focus=true#logs)

```
@temporalio/test:   replay › cancel-fake-progress-replay
@temporalio/test:   Rejected promise returned by test. Reason:
@temporalio/test:   UnexpectedError {
@temporalio/test:     message: 'channel closed',
@temporalio/test:   }
@temporalio/test:   › /Users/runner/work/sdk-typescript/sdk-typescript/packages/worker/lib/worker.js:887:54
@temporalio/test:   › /Users/runner/work/sdk-typescript/sdk-typescript/packages/worker/lib/tracing.js:65:26
@temporalio/test:   › NoopContextManager.with (/Users/runner/work/sdk-typescript/sdk-typescript/node_modules/@opentelemetry/api/build/src/context/NoopContextManager.js:36:24)
@temporalio/test:   › ContextAPI.with (/Users/runner/work/sdk-typescript/sdk-typescript/node_modules/@opentelemetry/api/build/src/api/context.js:71:54)
@temporalio/test:   › instrument (/Users/runner/work/sdk-typescript/sdk-typescript/packages/worker/lib/tracing.js:61:29)
@temporalio/test:   › /Users/runner/work/sdk-typescript/sdk-typescript/packages/worker/lib/worker.js:883:51
@temporalio/test:   › /Users/runner/work/sdk-typescript/sdk-typescript/packages/worker/lib/worker.js:352:33
@temporalio/test:   ─
@temporalio/test:   1 test failed
```

**Comment by bergundy** [comment]
Awesome work tracking all of this @lorensr I think some of these issues have already been solved.
Might be worth tracking each individual flake.

The new channel closed one worries me and could happen to users in production but it might just be during shutdown so it might not be too critical.

**Comment by bergundy** [comment]
Hmm.. nm looks like it happens in the replay worker, still troubling but not as much

**Comment by lorensr** [comment]
Got above channel closed failure a few times locally, and also this new version of it:

```
@temporalio/test:   replay › cancel-fake-progress-replay-nondeterministic
@temporalio/test:   lib/test-replay.js:68
@temporalio/test:    67:     hist.events[0].workflowExecutionStartedEventAttributes.workflowType.…
@temporalio/test:    68:     await t.throwsAsync(worker_1.Worker.runReplayHistory({
@temporalio/test:    69:         workflowsPath: require.resolve('./workflows'),
@temporalio/test:   Promise rejected with unexpected exception:
@temporalio/test:   UnexpectedError {
@temporalio/test:     message: 'channel closed',
@temporalio/test:   }
@temporalio/test:   Expected instance of:
@temporalio/test:   Function DeterminismViolationError {}
@temporalio/test:   › /Users/me/gh/sdk2/packages/worker/lib/worker.js:910:54
@temporalio/test:   › /Users/me/gh/sdk2/packages/worker/lib/tracing.js:65:26
@temporalio/test:   › NoopContextManager.with (/Users/me/gh/sdk2/node_modules/@opentelemetry/api/build/src/context/NoopContextManager.js:36:24)
@temporalio/test:   › ContextAPI.with (/Users/me/gh/sdk2/node_modules/@opentelemetry/api/build/src/api/context.js:71:54)
@temporalio/test:   › instrument (/Users/me/gh/sdk2/packages/worker/lib/tracing.js:61:29)
@temporalio/test:   › /Users/me/gh/sdk2/packages/worker/lib/worker.js:906:51
@temporalio/test:   › /Users/me/gh/sdk2/packages/worker/lib/worker.js:379:33
@temporalio/test:   ─
```

https://app.warp.dev/block/cnnzcwtjYDvLxKkYu7YEFK

**Comment by mjameswh** [comment]
@bergundy @lorensr Do you guys remember seeing any of these flakes recently? If not, I suggest that we close this issue now, and just track any further flake pattern in distinct, specific issues.

**Comment by bergundy** [comment]
I think we addressed all of the known flakes.
From time to time I see npm ci failing with an internal npm error and I’m considering moving from npm but we can track this separately.
