### ISSUE TITLE
[Bug] test-worker-no-workflows intermittent failure

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#529]
This happens some of the time:

`RUN_INTEGRATION_TESTS=1 npx ava packages/test/lib/test-worker-no-workflows.js`

```
2022-03-12T00:00:24.360Z [INFO] [temporal_sdk_core::worker::dispatcher] Shutting down worker on queue only-activities
2022-03-12T00:00:24.360Z [INFO] [temporal_sdk_core::worker::dispatcher] Shutting down worker on queue also-workflows
2022-03-12T00:00:24.362Z [INFO] Worker state changed { state: 'DRAINED' }
2022-03-12T00:00:24.362Z [INFO] Worker state changed { state: 'STOPPED' }
2022-03-12T00:00:29.360Z [ERROR] Worker failed {
  error: GracefulShutdownPeriodExpiredError: Timed out while waiting for worker to shutdown gracefully
      at /Users/me/gh/sdk-typescript/packages/worker/src/worker.ts:399:17
      at /Users/me/gh/sdk-typescript/node_modules/rxjs/src/internal/operators/map.ts:58:33
      at OperatorSubscriber._this._next (/Users/me/gh/sdk-typescript/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
      at OperatorSubscriber.Subscriber.next (/Users/me/gh/sdk-typescript/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
      at /Users/me/gh/sdk-typescript/node_modules/rxjs/src/internal/operators/mergeInternals.ts:85:24
      at OperatorSubscriber._this._next (/Users/me/gh/sdk-typescript/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
      at OperatorSubscriber.Subscriber.next (/Users/me/gh/sdk-typescript/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
      at /Users/me/gh/sdk-typescript/node_modules/rxjs/src/internal/operators/map.ts:58:20
      at OperatorSubscriber._this._next (/Users/me/gh/sdk-typescript/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
      at OperatorSubscriber.Subscriber.next (/Users/me/gh/sdk-typescript/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
}
2022-03-12T00:00:29.360Z [INFO] Worker state changed { state: 'FAILED' }
  Worker functions when asked not to run Workflows

  Rejected promise returned by test. Reason:

  GracefulShutdownPeriodExpiredError {
    message: 'Timed out while waiting for worker to shutdown gracefully',
  }

  › packages/worker/src/worker.ts:399:17
  › node_modules/rxjs/src/internal/operators/map.ts:58:33
  › OperatorSubscriber._this._next (node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
  › OperatorSubscriber.Subscriber.next (node_modules/rxjs/src/internal/Subscriber.ts:75:12)
  › node_modules/rxjs/src/internal/operators/mergeInternals.ts:85:24
  › OperatorSubscriber._this._next (node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
  › OperatorSubscriber.Subscriber.next (node_modules/rxjs/src/internal/Subscriber.ts:75:12)
  › node_modules/rxjs/src/internal/operators/map.ts:58:20
  › OperatorSubscriber._this._next (node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
  › OperatorSubscriber.Subscriber.next (node_modules/rxjs/src/internal/Subscriber.ts:75:12)

  ─

  1 test failed
  ```
  
  on latest `main` and `0.18.0`

**Comment by mjameswh** [comment]
Two recent occurrences:
- https://github.com/temporalio/sdk-typescript/actions/runs/3576905911/jobs/6016717992#step:13:9918
- One around 2022-11-07

<img width="1203" alt="Capture d’écran, le 2022-11-07 à 15 42 42" src="https://user-images.githubusercontent.com/6412169/204641761-5e8d422d-7c0e-4608-a954-d4464abaef90.png">

**Comment by mjameswh** [comment]
Haven't seen this error recently. Also, the Worker shutdown process has changed a lot since this was initially reported, so it seems very reasonable to think that this has already been fixed.
