### ISSUE TITLE
[Bug] Installing v0.23 I get error "Cannot find module '@temporalio/common/lib/converter/wrapped-payload-converter'"

### ISSUE THREAD

**Issue by davidtheclark** [temporalio/sdk-typescript#687]
### What are you really trying to do?

Update from 0.21 to 0.23.

### Describe the bug

I get error "Cannot find module '@temporalio/common/lib/converter/wrapped-payload-converter'".

```
> @watershed/temporal-worker@0.1.0 build-webpack-bundle /.../workspaces/temporal-worker
> node ../../build/workspaces/temporal-worker/build-webpack-bundle.js
node:internal/modules/cjs/loader:936
  throw err;
  ^
Error: Cannot find module '@temporalio/common/lib/converter/wrapped-payload-converter'
Require stack:
- /.../node_modules/.pnpm/@temporalio+workflow@0.23.0/node_modules/@temporalio/workflow/lib/internals.js
- /.../node_modules/.pnpm/@temporalio+workflow@0.23.0/node_modules/@temporalio/workflow/lib/workflow.js
- /.../node_modules/.pnpm/@temporalio+workflow@0.23.0/node_modules/@temporalio/workflow/lib/index.js
- /.../node_modules/.pnpm/@temporalio+worker@0.23.2/node_modules/@temporalio/worker/lib/worker.js
- /.../node_modules/.pnpm/@temporalio+worker@0.23.2/node_modules/@temporalio/worker/lib/index.js
- /.../build/workspaces/temporal-worker/build-webpack-bundle.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._resolveFilename (/.../node_modules/.pnpm/module-alias@2.2.2/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/.../node_modules/.pnpm/@temporalio+workflow@0.23.0/node_modules/@temporalio/workflow/lib/internals.js:17:37)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
undefined
    '/.../node_modules/.pnpm/@temporalio+workflow@0.23.0/node_modules/@temporalio/workflow/lib/internals.js',
    '/.../node_modules/.pnpm/@temporalio+workflow@0.23.0/node_modules/@temporalio/workflow/lib/workflow.js',
    '/.../node_modules/.pnpm/@temporalio+workflow@0.23.0/node_modules/@temporalio/workflow/lib/index.js',
    '/.../node_modules/.pnpm/@temporalio+worker@0.23.2/node_modules/@temporalio/worker/lib/worker.js',
    '/.../node_modules/.pnpm/@temporalio+worker@0.23.2/node_modules/@temporalio/worker/lib/index.js',
/.../workspaces/temporal-worker:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @watershed/temporal-worker@0.1.0 build-webpack-bundle: `node ../../build/workspaces/temporal-worker/build-webpack-bundle.js`
Exit status 1
    '/.../build/workspaces/temporal-worker/build-webpack-bundle.js'
  ]
}
```

It looks to me like [`@temporalio/workflow/lib/internals` depends on `@temporalio/common`](https://github.com/temporalio/sdk-typescript/blob/31eb76a8849ef046b2978bc77b78248eb1ae32d6/packages/workflow/src/internals.ts), but [`@temporalio/common` is not defined as a dependency in `workflow/package.json`.](https://github.com/temporalio/sdk-typescript/blob/31eb76a8849ef046b2978bc77b78248eb1ae32d6/packages/workflow/package.json)

### Environment/Versions

- OS and processor: Mac
- Temporal Version: 0.21 -> 0.23
- Are you using Docker or Kubernetes or building Temporal from source? Docker

I'm using pnpm to manage Node dependencies.

**Comment by lorensr** [comment]
Thanks for reporting! That particular import isn't used anymore on latest `main`, but we do have other imports to /common from /workflow, so I opened #688 to fix.
