### ISSUE TITLE
[Bug] Stress test: namespace not found

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#807]
```
Status server listening on { address: '::', family: 'IPv6', port: 6666 }
WFs complete (0/100) -- WFs/s curr 0.0 (acc 0.0) -- CPU 208%, MEM 231.52MB  [TransportError: TonicError(Status { code: NotFound, message: "Namespace ce58a569-bb6c-4fa3-b0bd-cd22a005f935 is not found.", details: b"\x08\x05\x12<Namespace ce58a569-bb6c-4fa3-b0bd-cd22a005f935 is not found.\x1as\nItype.googleapis.com/temporal.api.errordetails.v1.NamespaceNotFoundFailure\x12&\n$ce58a569-bb6c-4fa3-b0bd-cd22a005f935", metadata: MetadataMap { headers: {"content-type": "application/grpc"} }, source: None })]
Load all-in-one caught error Error: ChildProcessError: Process failed
    at main (/home/runner/_work/sdk-typescript/sdk-typescript/packages/test/lib/load/all-in-one.js:70:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
/home/runner/_work/sdk-typescript/sdk-typescript/packages/test/lib/load/all-scenarios.js:107
            throw new Error(`Test failed with status: ${status}, signal: ${signal}, error: ${error?.message}`);
            ^

Error: Test failed with status: 1, signal: null, error: undefined
    at runScenarios (/home/runner/_work/sdk-typescript/sdk-typescript/packages/test/lib/load/all-scenarios.js:107:19)
    at Object.<anonymous> (/home/runner/_work/sdk-typescript/sdk-typescript/packages/test/lib/load/run-all-stress-ci-scenarios.js:28:34)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
Error: Process completed with exit code 1.
```

[stress-tests / stress-test](https://github.com/temporalio/sdk-typescript/runs/7696954237?check_suite_focus=true#logs)

[stress-tests / stress-test](https://github.com/temporalio/sdk-typescript/runs/7697122126?check_suite_focus=true#logs)

**Comment by bergundy** [comment]
Thanks for tracking @lorensr I've seen this before.
Not sure if there's a better solution on the server side for this or if we need to work around this (by sleeping?).
Temporalite might be another good option to mitigate these issues.

**Comment by mjameswh** [comment]
No recent occurrence of this one, and I believe this has been resolved a long time ago by adding a "wait for namespace ready" function before running tests.
