### ISSUE TITLE
Jest does not exit due to open handle in temporal

### ISSUE THREAD

**Issue by bennidhamma** [temporalio/sdk-typescript#851]
### What are you really trying to do?

Jest is not exiting correctly due to an open handle in temporal. In and of itself not necessarily the worst thing in the world. but... I'm trying to collect code coverage with nyc, and it [seems](https://github.com/istanbuljs/nyc/issues/762) like nyc prefers to have processes exit cleanly before it attempts to collect coverage information.

### Describe the bug

I don't really understand what's going on. here's a stack trace though:

```
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  neon threadsafe function

      93 | export { DataConverter, defaultPayloadConverter, errors };
      94 |
    > 95 | native.registerErrors(errors);
         |        ^
      96 | /**
      97 |  * The worker's possible states
      98 |  * * `INITIALIZED` - The initial state of the Worker after calling {@link Worker.create} and successful connection to the server

      at Object.<anonymous> (../../sdk-typescript/packages/worker/src/worker.ts:95:8)
      at Object.<anonymous> (../../sdk-typescript/packages/worker/src/index.ts:29:1)
      at Object.<anonymous> (../../sdk-typescript/packages/testing/src/index.ts:20:1)
      at Object.<anonymous> (test/unit/scheduling/v2/core/operations/restrict_appt_operating_hours_v2.test.ts:2:1)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:317:13)
      at runJest (node_modules/@jest/core/build/runJest.js:407:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:339:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:190:3)
```

### Minimal Reproduction

If you add `--detectOpenHandles` to the jest script in the activies-examples sample you can see the same error there.

### Environment/Versions

- OS and processor: Linux
- Temporal Version: 1.1.0
- using temporal test server

**Comment by lorensr** [comment]
We're not sure yet either, tracking here: https://github.com/temporalio/samples-typescript/issues/189

**Comment by bennidhamma** [comment]
oops. i'm sorry I didn't search first.
