### ISSUE TITLE
[Bug] Error on Render: `TypeError: failed to downcast any`

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#877]
### What are you really trying to do?

Use `env: node` on Render:

https://github.com/anthonywong555/temporal-render-simple/blob/0dd74e4628c87e7663002cb93f8f64c0c328d4be/render.yaml#L107-L120

or `env: docker` with our recommended Dockerfile:

https://github.com/anthonywong555/temporalio-hello-world-js-app-worker-docker/blob/master/Dockerfile

With this simple sample:

https://github.com/anthonywong555/temporalio-hello-world-js

### Describe the bug

```
Sep 20 11:40:44 AM  ==> Detected Node version 16.17.0
Sep 20 11:40:44 AM  ==> Starting service with 'npm run start.watch'
Sep 20 11:40:45 AM  
Sep 20 11:40:45 AM  > hello-world-js@0.1.0 start.watch
Sep 20 11:40:45 AM  > nodemon src/worker.js
Sep 20 11:40:45 AM  
Sep 20 11:40:45 AM  [nodemon] 2.0.20
Sep 20 11:40:45 AM  [nodemon] to restart at any time, enter `rs`
Sep 20 11:40:45 AM  [nodemon] watching path(s): src/**/*
Sep 20 11:40:45 AM  [nodemon] watching extensions: js,mjs,json
Sep 20 11:40:45 AM  [nodemon] starting `node src/worker.js`
Sep 20 11:40:47 AM  2022-09-20T15:40:47.201Z [INFO] Creating worker {
Sep 20 11:40:47 AM    options: {
Sep 20 11:40:47 AM      namespace: 'default',
Sep 20 11:40:47 AM      shutdownGraceTime: '10s',
Sep 20 11:40:47 AM      maxConcurrentActivityTaskExecutions: 100,
Sep 20 11:40:47 AM      maxConcurrentLocalActivityExecutions: 100,
Sep 20 11:40:47 AM      enableNonLocalActivities: true,
Sep 20 11:40:47 AM      maxConcurrentWorkflowTaskExecutions: 100,
Sep 20 11:40:47 AM      stickyQueueScheduleToStartTimeout: '10s',
Sep 20 11:40:47 AM      maxHeartbeatThrottleInterval: '60s',
Sep 20 11:40:47 AM      defaultHeartbeatThrottleInterval: '30s',
Sep 20 11:40:47 AM      isolateExecutionTimeout: '5s',
Sep 20 11:40:47 AM      workflowThreadPoolSize: 8,
Sep 20 11:40:47 AM      maxCachedWorkflows: 250,
Sep 20 11:40:47 AM      enableSDKTracing: false,
Sep 20 11:40:47 AM      showStackTraceSources: false,
Sep 20 11:40:47 AM      debugMode: false,
Sep 20 11:40:47 AM      interceptors: { activityInbound: [Array], workflowModules: [Array] },
Sep 20 11:40:47 AM      sinks: { defaultWorkerLogger: [Object] },
Sep 20 11:40:47 AM      workflowsPath: '/opt/render/project/src/src/workflows.js',
Sep 20 11:40:47 AM      activities: [Module: null prototype] { greet: [AsyncFunction: greet] },
Sep 20 11:40:47 AM      taskQueue: 'hello-javascript',
Sep 20 11:40:47 AM      shutdownGraceTimeMs: 10000,
Sep 20 11:40:47 AM      stickyQueueScheduleToStartTimeoutMs: 10000,
Sep 20 11:40:47 AM      isolateExecutionTimeoutMs: 5000,
Sep 20 11:40:47 AM      maxHeartbeatThrottleIntervalMs: 60000,
Sep 20 11:40:47 AM      defaultHeartbeatThrottleIntervalMs: 30000,
Sep 20 11:40:47 AM      loadedDataConverter: { payloadConverter: [DefaultPayloadConverter], payloadCodecs: [] }
Sep 20 11:40:47 AM    }
Sep 20 11:40:47 AM  }
Sep 20 11:40:52 AM  2022-09-20T15:40:52.685Z [INFO] asset workflow-bundle-291cb9f0d373c32fd94c.js 683 KiB [emitted] [immutable] (name: main)
Sep 20 11:40:52 AM  2022-09-20T15:40:52.689Z [INFO] runtime modules 1.77 KiB 4 modules
Sep 20 11:40:52 AM  2022-09-20T15:40:52.690Z [INFO] modules by path ./node_modules/@temporalio/ 162 KiB
Sep 20 11:40:52 AM  2022-09-20T15:40:52.690Z [INFO]   modules by path ./node_modules/@temporalio/workflow/ 96.5 KiB 13 modules
Sep 20 11:40:52 AM  2022-09-20T15:40:52.690Z [INFO]   modules by path ./node_modules/@temporalio/common/lib/ 48.7 KiB 10 modules
Sep 20 11:40:52 AM  2022-09-20T15:40:52.690Z [INFO]   modules by path ./node_modules/@temporalio/internal-workflow-common/lib/*.js 14.4 KiB
Sep 20 11:40:52 AM  2022-09-20T15:40:52.690Z [INFO]     ./node_modules/@temporalio/internal-workflow-common/lib/index.js 1.3 KiB [built] [code generated]
Sep 20 11:40:52 AM  2022-09-20T15:40:52.690Z [INFO]     + 9 modules
Sep 20 11:40:52 AM  2022-09-20T15:40:52.691Z [INFO]   ./node_modules/@temporalio/worker/lib/workflow-log-interceptor.js 2.25 KiB [built] [code generated]
Sep 20 11:40:52 AM  2022-09-20T15:40:52.691Z [INFO] modules by path ./src/*.js 773 bytes
Sep 20 11:40:52 AM  2022-09-20T15:40:52.692Z [INFO]   ./src/workflows-autogenerated-entrypoint.js 524 bytes [built] [code generated]
Sep 20 11:40:52 AM  2022-09-20T15:40:52.692Z [INFO]   ./src/workflows.js 249 bytes [built] [code generated]
Sep 20 11:40:52 AM  2022-09-20T15:40:52.692Z [INFO] __temporal_custom_payload_converter (ignored) 15 bytes [built] [code generated]
Sep 20 11:40:52 AM  2022-09-20T15:40:52.692Z [INFO] ./node_modules/long/umd/index.js 43.1 KiB [built] [code generated]
Sep 20 11:40:52 AM  2022-09-20T15:40:52.692Z [INFO] ./node_modules/ms/index.js 2.95 KiB [built] [code generated]
Sep 20 11:40:52 AM  2022-09-20T15:40:52.693Z [INFO] webpack 5.74.0 compiled successfully in 4264 ms
Sep 20 11:40:52 AM  2022-09-20T15:40:52.699Z [INFO] Workflow bundle created { size: '0.67MB' }
Sep 20 11:41:00 AM  TypeError: failed to downcast any to neon::types::boxed::JsBox<core::cell::RefCell<core::option::Option<temporal_sdk_typescript_bridge::Client>>>
Sep 20 11:41:00 AM      at node:internal/util:361:7
Sep 20 11:41:00 AM      at new Promise (<anonymous>)
Sep 20 11:41:00 AM      at temporal_sdk_typescript_bridge::worker_new (node:internal/util:347:12)
Sep 20 11:41:00 AM      at Runtime.registerWorker (/opt/render/project/src/node_modules/@temporalio/worker/lib/runtime.js:274:73)
Sep 20 11:41:00 AM      at Function.create (/opt/render/project/src/node_modules/@temporalio/worker/lib/worker.js:88:44)
Sep 20 11:41:00 AM      at Function.create (/opt/render/project/src/node_modules/@temporalio/worker/lib/worker.js:178:51)
Sep 20 11:41:00 AM      at async run (file:///opt/render/project/src/src/worker.js:9:18)
Sep 20 11:41:01 AM  [nodemon] app crashed - waiting for file changes before starting...
```

### Environment/Versions

https://render.com/docs/native-environments

### Additional context

> It’s an error in the bridge, but the output isn’t great. We should upgrade the places these downcasts happen to include more context.
—Spencer

**Comment by lorensr** [comment]
Issue was lack of `NativeConnection` passed to Worker.create:

https://github.com/anthonywong555/temporalio-hello-world-js-app-worker-docker/blob/b3ae3a7c8b6498915896f4b049049a7feb6633cf/src/worker.js#L13

Action items:

- We should upgrade the places these downcasts happen to include more context.
- Add input validation to `Worker.create` (and everywhere else 😄)

**Comment by bergundy** [comment]
Failed to downcast is input validation, it’s a type error.
We can add more input validation at worker creation time but I think that’s overkill, an IDE should catch this.
